### ISSUE TITLE
Energy Calibration output image files need "detector_name" included.

### ISSUE THREAD

**Issue by arwoll** [CHESSComputing/ChessAnalysisPipeline#101]
In the spring 2024 branch, Rolf helped me change line 1266 from this:

                figfile = os.path.join(outputdir, 'energy_calibration_fit.png')

to this:

                figfile = os.path.join(outputdir, f'energy_calibration_fit_{detector.detector_name}.png')

to disambiguate output files when fitting more than one detector. (I forgot to make a new branch prior to making this change so am suggesting it here rather than with a pull request...)

**Comment by rolfverberg** [comment]
Done
