### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by keara-soloway** [CHESSComputing/ChessAnalysisPipeline#29]
Add unit tests for the CHAP module; integrate their execution with CI/CD.

- [ ] Enumerate testable entities
- [ ] Decide what metrics need to be tested on each one
- [ ] Implement

**Comment by vkuznet** [comment]
@keara-soloway , please see my initial PR https://github.com/CHESSComputing/ChessAnalysisPipeline/pull/35 and extend it further.

**Comment by vkuznet** [comment]
The unittest should cover CHAP component functionality. The `test/data` area should be used to store test data of any form. And, test should check for data types, and internal data-flow.
